app:
  name: auth
  secret: secret
db:
  adapter: postgresql
  host: localhost
  user: postgres
  password: postgres
pagination:
  page_size: 10
rabbitmq:
  host: <%= ENV['RABBITMQ_HOST']%>
  user: <%= ENV['RABBITMQ_USER']%>
  password: <%= ENV['RABBITMQ_PASS']%>
  consumer_pool: 10
logger:
  path: log/app.log
  level: info
